spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sf_prod
    password: elglorioso_prod
    username: sf_prod_user
    platform: mysql
  jpa:
    hibernate:
      ddl_auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
  batch:
    job:
      enabled: false
