spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sf_dev
    password: elglorioso_dev
    username: sf_dev_user
    platform: mysql
  jpa:
    hibernate:
      ddl_auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql